services:
  cache:
    image: redis:7.2.4-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "6379:6379"
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./container/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env
    ports:
      - "5050:80"
    depends_on:
      - db
